# Words for hangman game
words=('Aardvark', 'Albatross', 'Alligator', 'Alpaca', 'Ant', 'Anteater', 'Antelope', 'Ape', 'Armadillo', 
    'Baboon', 'Badger', 'Barracuda', 'Bat', 'Bear', 'Beaver', 'Bee', 'Bison', 'Boar', 'Buffalo', 
    'Butterfly', 'Camel', 'Capybara', 'Caribou', 'Cassowary', 'Cat', 'Caterpillar', 'Chameleon', 
    'Cheetah', 'Chicken', 'Chimpanzee', 'Chinchilla', 'Clam', 'Cobra', 'Cockroach', 'Cod', 'Coyote', 
    'Crab', 'Crane', 'Crocodile', 'Crow', 'Cuckoo', 'Deer', 'Dingo', 'Dinosaur', 'Dog', 'Dolphin', 
    'Donkey', 'Dove', 'Dragonfly', 'Duck', 'Dugong', 'Eagle', 'Echidna', 'Eel', 'Eland', 'Elephant', 
    'Elk', 'Emu', 'Falcon', 'Ferret', 'Finch', 'Firefly', 'Fish', 'Flamingo', 'Flea', 'Fly', 'Fox', 
    'Frog', 'Gazelle', 'Gecko', 'Gerbil', 'Gibbon', 'Giraffe', 'Gnat', 'Gnu', 'Goat', 'Goldfish', 
    'Goose', 'Gorilla', 'Goshawk', 'Grasshopper', 'Grouse', 'Guanaco', 'Gull', 'Hamster', 'Hare', 
    'Hawk', 'Hedgehog', 'Heron', 'Herring', 'Hippopotamus', 'Hornet', 'Horse', 'Hummingbird', 'Hyena', 
    'Ibex', 'Ibis', 'Iguana', 'Impala', 'Jackal', 'Jaguar', 'Jay', 'Jellyfish', 'Kangaroo', 'Kingfisher', 
    'Koala', 'Komodo Dragon', 'Kookaburra', 'Kouprey', 'Kudu', 'Ladybug', 'Lapwing', 'Lark', 'Lemur', 
    'Leopard', 'Lion', 'Llama', 'Lobster', 'Locust', 'Loris', 'Louse', 'Lyrebird', 'Macaw', 'Magpie', 
    'Mallard', 'Manatee', 'Mandrill', 'Mantis', 'Marlin', 'Marmot', 'Meerkat', 'Mink', 'Mole', 'Mongoose', 
    'Monkey', 'Moose', 'Mosquito', 'Moth', 'Mouse', 'Mule', 'Narwhal', 'Newt', 'Nightingale', 'Octopus', 
    'Okapi', 'Opossum', 'Oryx', 'Ostrich', 'Otter', 'Owl', 'Ox', 'Oyster', 'Panther', 'Parrot', 
    'Partridge', 'Peafowl', 'Pelican', 'Penguin', 'Pheasant', 'Pig', 'Pigeon', 'Platypus', 'Pony', 
    'Porcupine', 'Porpoise', 'Quail', 'Quelea', 'Quokka', 'Rabbit', 'Raccoon', 'Rail', 'Ram', 'Rat', 
    'Rattlesnake', 'Raven', 'Reindeer', 'Rhinoceros', 'Rook', 'Salamander', 'Salmon', 'Sandpiper', 
    'Sardine', 'Scorpion', 'Sea Lion', 'Sea Urchin', 'Seahorse', 'Seal', 'Shark', 'Sheep', 'Shrew', 
    'Shrimp', 'Skunk', 'Sloth', 'Snail', 'Snake', 'Sparrow', 'Spider', 'Spoonbill', 'Squid', 'Squirrel', 
    'Starling', 'Stingray', 'Stork', 'Swallow', 'Swan', 'Tapir', 'Tarsier', 'Termite', 'Tiger', 'Toad', 
    'Trout', 'Turkey', 'Turtle', 'Viper', 'Vulture', 'Wallaby', 'Walrus', 'Wasp', 'Weasel', 'Whale', 
    'Wildebeest', 'Wolf', 'Wolverine', 'Wombat', 'Woodpecker', 'Worm', 'Wren', 'Yak', 'Zebra')